version: '3'
volumes:
  data:

networks:
  dbflask:
    driver: bridge

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    networks:
      - dbflask

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bdflasksqlalchemy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dbflask
